version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - monopoly-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_monopoly_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/src/config/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      timeout: 20s
      retries: 10
      start_period: 10s
    networks:
      - monopoly-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5001"
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db_monopoly_tracker
      - FRONTEND_URL=http://monopolytracker.local:8080
    networks:
      - monopoly-network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

networks:
  monopoly-network:
    driver: bridge